model:
        n_jobs: -1
        estimators: 100
        random_state: 42
data:
        compression: bz2
        compression_level: 3
        kaggle: /twdata/kaggle
        parquet: /twdata/parquet
        modeldir: /twdata/model
        featuredir: /twdata/features
        source: jacksoncrow/stock-market-dataset
logging:
        logfile: /twdata/logs/twdataeng.log
        format: '%(asctime)s - %(levelname)s - %(message)s'
        debuglevel: 0

